// Emoji database with names for searchable emojis
export const EMOJI_DATABASE = [
  { emoji: '😀', name: 'grinning face' },
  { emoji: '😃', name: 'grinning face with big eyes' },
  { emoji: '😄', name: 'grinning face with smiling eyes' },
  { emoji: '😁', name: 'beaming face with smiling eyes' },
  { emoji: '😆', name: 'grinning squinting face' },
  { emoji: '😅', name: 'grinning face with sweat' },
  { emoji: '😂', name: 'face with tears of joy' },
  { emoji: '🤣', name: 'rolling on the floor laughing' },
  { emoji: '😊', name: 'smiling face with smiling eyes' },
  { emoji: '😇', name: 'smiling face with halo' },
  { emoji: '🙂', name: 'slightly smiling face' },
  { emoji: '🙃', name: 'upside down face' },
  { emoji: '😉', name: 'winking face' },
  { emoji: '😌', name: 'relieved face' },
  { emoji: '😍', name: 'smiling face with heart eyes' },
  { emoji: '🥰', name: 'smiling face with hearts' },
  { emoji: '😘', name: 'face blowing a kiss' },
  { emoji: '😗', name: 'kissing face' },
  { emoji: '😙', name: 'kissing face with smiling eyes' },
  { emoji: '😚', name: 'kissing face with closed eyes' },
  { emoji: '😋', name: 'face savoring food' },
  { emoji: '😛', name: 'face with tongue' },
  { emoji: '😝', name: 'squinting face with tongue' },
  { emoji: '😜', name: 'winking face with tongue' },
  { emoji: '🤪', name: 'zany face' },
  { emoji: '🤨', name: 'face with raised eyebrow' },
  { emoji: '🧐', name: 'face with monocle' },
  { emoji: '🤓', name: 'nerd face' },
  { emoji: '😎', name: 'smiling face with sunglasses' },
  { emoji: '🤩', name: 'star struck' },
  { emoji: '🥳', name: 'partying face' },
  { emoji: '😏', name: 'smirking face' },
  { emoji: '😒', name: 'unamused face' },
  { emoji: '😞', name: 'disappointed face' },
  { emoji: '😔', name: 'pensive face' },
  { emoji: '😟', name: 'worried face' },
  { emoji: '😕', name: 'confused face' },
  { emoji: '🙁', name: 'slightly frowning face' },
  { emoji: '☹️', name: 'frowning face' },
  { emoji: '😣', name: 'persevering face' },
  { emoji: '😖', name: 'confounded face' },
  { emoji: '😫', name: 'tired face' },
  { emoji: '😩', name: 'weary face' },
  { emoji: '🥺', name: 'pleading face' },
  { emoji: '😢', name: 'crying face' },
  { emoji: '😭', name: 'loudly crying face' },
  { emoji: '😤', name: 'face with steam from nose' },
  { emoji: '😠', name: 'angry face' },
  { emoji: '😡', name: 'pouting face' },
  { emoji: '🤬', name: 'face with symbols on mouth' },
  { emoji: '🤯', name: 'exploding head' },
  { emoji: '😳', name: 'flushed face' },
  { emoji: '🥵', name: 'hot face' },
  { emoji: '🥶', name: 'cold face' },
  { emoji: '😱', name: 'face screaming in fear' },
  { emoji: '😨', name: 'fearful face' },
  { emoji: '😰', name: 'anxious face with sweat' },
  { emoji: '😥', name: 'sad but relieved face' },
  { emoji: '😓', name: 'downcast face with sweat' },
  { emoji: '🤗', name: 'hugging face' },
  { emoji: '🤔', name: 'thinking face' },
  { emoji: '🤭', name: 'face with hand over mouth' },
  { emoji: '🤫', name: 'shushing face' },
  { emoji: '🤥', name: 'lying face' },
  { emoji: '😶', name: 'face without mouth' },
  { emoji: '😐', name: 'neutral face' },
  { emoji: '😑', name: 'expressionless face' },
  { emoji: '😯', name: 'hushed face' },
  { emoji: '😦', name: 'frowning face with open mouth' },
  { emoji: '😧', name: 'anguished face' },
  { emoji: '😮', name: 'face with open mouth' },
  { emoji: '😲', name: 'astonished face' },
  { emoji: '🥱', name: 'yawning face' },
  { emoji: '😴', name: 'sleeping face' },
  { emoji: '🤤', name: 'drooling face' },
  { emoji: '😪', name: 'sleepy face' },
  { emoji: '😵', name: 'dizzy face' },
  { emoji: '🤐', name: 'zipper mouth face' },
  { emoji: '🥴', name: 'woozy face' },
  { emoji: '🤢', name: 'nauseated face' },
  { emoji: '🤮', name: 'face vomiting' },
  { emoji: '🤧', name: 'sneezing face' },
  { emoji: '😷', name: 'face with medical mask' },
  { emoji: '🤒', name: 'face with thermometer' },
  { emoji: '🤕', name: 'face with head bandage' },
  { emoji: '🤑', name: 'money mouth face' },
  { emoji: '🤠', name: 'cowboy hat face' },
  { emoji: '💩', name: 'pile of poo' },
  { emoji: '🤡', name: 'clown face' },
  { emoji: '👹', name: 'ogre' },
  { emoji: '👺', name: 'goblin' },
  { emoji: '👻', name: 'ghost' },
  { emoji: '👽', name: 'alien' },
  { emoji: '👾', name: 'alien monster' },
  { emoji: '🤖', name: 'robot' },
  { emoji: '😺', name: 'grinning cat' },
  { emoji: '😸', name: 'grinning cat with smiling eyes' },
  { emoji: '😹', name: 'cat with tears of joy' },
  { emoji: '😻', name: 'heart eyes cat' },
  { emoji: '😼', name: 'cat with wry smile' },
  { emoji: '😽', name: 'kissing cat' },
  { emoji: '🙀', name: 'weary cat' },
  { emoji: '😿', name: 'crying cat' },
  { emoji: '😾', name: 'pouting cat' },
  { emoji: '🙈', name: 'see no evil monkey' },
  { emoji: '🙉', name: 'hear no evil monkey' },
  { emoji: '🙊', name: 'speak no evil monkey' },
  { emoji: '💌', name: 'love letter' },
  { emoji: '💘', name: 'heart with arrow' },
  { emoji: '💝', name: 'heart with ribbon' },
  { emoji: '💖', name: 'sparkling heart' },
  { emoji: '💗', name: 'growing heart' },
  { emoji: '💓', name: 'beating heart' },
  { emoji: '💞', name: 'revolving hearts' },
  { emoji: '💕', name: 'two hearts' },
  { emoji: '💟', name: 'heart decoration' },
  { emoji: '❣️', name: 'heart exclamation' },
  { emoji: '💔', name: 'broken heart' },
  { emoji: '❤️', name: 'red heart' },
  { emoji: '🧡', name: 'orange heart' },
  { emoji: '💛', name: 'yellow heart' },
  { emoji: '💚', name: 'green heart' },
  { emoji: '💙', name: 'blue heart' },
  { emoji: '💜', name: 'purple heart' },
  { emoji: '🖤', name: 'black heart' },
  { emoji: '💯', name: 'hundred points' },
  { emoji: '💢', name: 'anger symbol' },
  { emoji: '💥', name: 'collision' },
  { emoji: '💫', name: 'dizzy' },
  { emoji: '💦', name: 'sweat droplets' },
  { emoji: '💨', name: 'dashing away' },
  { emoji: '🕳️', name: 'hole' },
  { emoji: '💬', name: 'speech balloon' },
  { emoji: '🗨️', name: 'left speech bubble' },
  { emoji: '🗯️', name: 'right anger bubble' },
  { emoji: '💭', name: 'thought balloon' },
  { emoji: '💤', name: 'zzz' },
  { emoji: '🌐', name: 'globe with meridians' },
  { emoji: '🗺️', name: 'world map' },
  { emoji: '🧭', name: 'compass' },
  { emoji: '🏔️', name: 'mountain' },
  { emoji: '⛰️', name: 'mountain' },
  { emoji: '🌋', name: 'volcano' },
  { emoji: '🗻', name: 'mount fuji' },
  { emoji: '🏕️', name: 'camping' },
  { emoji: '🏖️', name: 'beach with umbrella' },
  { emoji: '🏜️', name: 'ert' },
  { emoji: '🏝️', name: 'ert island' },
  { emoji: '🏞️', name: 'national park' },
  { emoji: '🏟️', name: 'stadium' },
  { emoji: '🏛️', name: 'classical building' },
  { emoji: '🏗️', name: 'building construction' },
  { emoji: '🧱', name: 'brick' },
  { emoji: '🪨', name: 'rock' },
  { emoji: '🪵', name: 'wood' },
  { emoji: '🛖', name: 'hut' },
  { emoji: '🏘️', name: 'houses' },
  { emoji: '🏚️', name: 'derelict house' },
  { emoji: '🏠', name: 'house' },
  { emoji: '🏡', name: 'house with garden' },
  { emoji: '🏢', name: 'office building' },
  { emoji: '🏣', name: 'japanese post office' },
  { emoji: '🏤', name: 'post office' },
  { emoji: '🏥', name: 'hospital' },
  { emoji: '🏦', name: 'bank' },
  { emoji: '🏨', name: 'hotel' },
  { emoji: '🏩', name: 'love hotel' },
  { emoji: '🏪', name: 'convenience store' },
  { emoji: '🏫', name: 'school' },
  { emoji: '🏬', name: 'department store' },
  { emoji: '🏭', name: 'factory' },
  { emoji: '🏯', name: 'japanese castle' },
  { emoji: '🏰', name: 'castle' },
  { emoji: '💒', name: 'wedding' },
  { emoji: '🗼', name: 'tokyo tower' },
  { emoji: '🗽', name: 'statue of liberty' },
  { emoji: '⛪', name: 'church' },
  { emoji: '🕌', name: 'mosque' },
  { emoji: '🛕', name: 'hindu temple' },
  { emoji: '🕍', name: 'synagogue' },
  { emoji: '⛩️', name: 'shinto shrine' },
  { emoji: '🕋', name: 'kaaba' },
  { emoji: '⛲', name: 'fountain' },
  { emoji: '⛺', name: 'tent' },
  { emoji: '🌁', name: 'foggy' },
  { emoji: '🌃', name: 'night with stars' },
  { emoji: '🏙️', name: 'cityscape' },
  { emoji: '🌄', name: 'sunrise over mountains' },
  { emoji: '🌅', name: 'sunrise' },
  { emoji: '🌆', name: 'cityscape at dusk' },
  { emoji: '🌇', name: 'sunset' },
  { emoji: '🌉', name: 'bridge at night' },
  { emoji: '♨️', name: 'hot springs' },
  { emoji: '🎠', name: 'carousel horse' },
  { emoji: '🎡', name: 'ferris wheel' },
  { emoji: '🎢', name: 'roller coaster' },
  { emoji: '💈', name: 'barber pole' },
  { emoji: '🎪', name: 'circus tent' },
  { emoji: '🚂', name: 'locomotive' },
  { emoji: '🚃', name: 'railway car' },
  { emoji: '🚄', name: 'high speed train' },
  { emoji: '🚅', name: 'bullet train' },
  { emoji: '🚆', name: 'train' },
  { emoji: '🚇', name: 'metro' },
  { emoji: '🚈', name: 'light rail' },
  { emoji: '🚉', name: 'station' },
  { emoji: '🚊', name: 'tram' },
  { emoji: '🚝', name: 'monorail' },
  { emoji: '🚞', name: 'mountain railway' },
  { emoji: '🚋', name: 'tram car' },
  { emoji: '🚌', name: 'bus' },
  { emoji: '🚍', name: 'oncoming bus' },
  { emoji: '🚎', name: 'trolleybus' },
  { emoji: '🚐', name: 'minibus' },
  { emoji: '🚑', name: 'ambulance' },
  { emoji: '🚒', name: 'fire engine' },
  { emoji: '🚓', name: 'police car' },
  { emoji: '🚔', name: 'oncoming police car' },
  { emoji: '🚕', name: 'taxi' },
  { emoji: '🚖', name: 'oncoming taxi' },
  { emoji: '🚗', name: 'automobile' },
  { emoji: '🚘', name: 'oncoming automobile' },
  { emoji: '🚙', name: 'sport utility vehicle' },
  { emoji: '🚚', name: 'delivery truck' },
  { emoji: '🚛', name: 'articulated lorry' },
  { emoji: '🚜', name: 'tractor' },
  { emoji: '🏎️', name: 'racing car' },
  { emoji: '🏍️', name: 'motorcycle' },
  { emoji: '🛵', name: 'motor scooter' },
  { emoji: '🦽', name: 'manual wheelchair' },
  { emoji: '🦼', name: 'motorized wheelchair' },
  { emoji: '🛴', name: 'kick scooter' },
  { emoji: '🚲', name: 'bicycle' },
  { emoji: '🛺', name: 'auto rickshaw' },
  { emoji: '🛻', name: 'pickup truck' },
  { emoji: '🚁', name: 'helicopter' },
  { emoji: '🚟', name: 'suspension railway' }
];
