/**
 * pN Connect Component
 * Prompts visitors to connect their pN to unlock engagement features
 * Uses OAuth 2.0 authorization code flow with popup window (like Google OAuth)
 */

import React, { useEffect } from 'react';
import { Lock, Heart, MessageCircle, Share2 } from 'lucide-react';
import { useUserState } from '../contexts/UserStateContext';
import { PNOAuthService } from '../services/pnOAuthService';
import { useToast } from '../hooks/useToast';

interface PNConnectProps {
  onConnect?: () => void;
  compact?: boolean;
}

export function PNConnect({ onConnect, compact = false }: PNConnectProps) {
  const { setUnlocked, userState } = useUserState();
  const { success, error: showError } = useToast();

  // Listen for OAuth callback from popup
  useEffect(() => {
    const handleMessage = async (event: MessageEvent) => {
      // Verify origin
      if (event.origin !== window.location.origin) {
        return;
      }

      if (event.data.type === 'oauth_callback') {
        const { code, error, state } = event.data;

        if (error) {
          showError(error === 'access_denied' ? 'Authorization denied' : 'Authorization failed');
          return;
        }

        if (!code) {
          return;
        }

        try {
          // Exchange code for tokens
          const tokenResponse = await PNOAuthService.exchangeCodeForToken(code);
          
          // Get user info
          const userInfo = await PNOAuthService.getUserInfo(tokenResponse.access_token);

          // Load feed tokens for owned feeds
          let feedTokens: any[] = [];
          try {
            if (userInfo.pn_identifier) {
              const feedTokensResponse = await fetch(`${process.env.REACT_APP_API_ENDPOINT || 'https://api.parnoir.com'}/api/feeds/tokens`, {
                headers: {
                  'Authorization': `Bearer ${tokenResponse.access_token}`
                }
              });
              
              if (feedTokensResponse.ok) {
                const feedTokensData = await feedTokensResponse.json();
                feedTokens = feedTokensData.feedTokens || [];
                console.log(`✅ Loaded ${feedTokens.length} feed tokens`);
              } else {
                console.warn('⚠️ Failed to load feed tokens:', feedTokensResponse.status);
              }
            }
          } catch (error) {
            console.error('❌ Error loading feed tokens:', error);
            // Don't fail auth if feed tokens can't be loaded
          }

          // Create and save session
          // Note: pN name is NOT stored - it's a secret
          const session = {
            accessToken: tokenResponse.access_token,
            refreshToken: tokenResponse.refresh_token,
            expiresAt: Date.now() + (tokenResponse.expires_in * 1000),
            did: userInfo.did,
            pnIdentifier: userInfo.pn_identifier, // Store pnIdentifier if available
            nickname: userInfo.nickname, // Optional nickname if available
            feedTokens: feedTokens // Store feed tokens for context switching
          };

          PNOAuthService.saveSession(session);

          // Update user state - use pn_identifier if available, otherwise fall back to DID
          const identifier = userInfo.pn_identifier || userInfo.did;
          if (!identifier) {
            throw new Error('No identifier available from user info');
          }
          setUnlocked(identifier);
          success('Successfully connected your pN!');
          onConnect?.();
        } catch (err: any) {
          console.error('OAuth callback error:', err);
          showError(err.message || 'Failed to complete authorization');
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => {
      window.removeEventListener('message', handleMessage);
    };
  }, [setUnlocked, success, showError, onConnect]);

  const handleConnect = () => {
    // Generate OAuth authorization URL
    const authUrl = PNOAuthService.getAuthorizationUrl({
      scope: ['openid', 'profile'],
      state: undefined // Will be generated by getAuthorizationUrl
    });

    // Open popup window (like Google OAuth)
    const popupWidth = 500;
    const popupHeight = 700;
    const left = (window.screen.width - popupWidth) / 2;
    const top = (window.screen.height - popupHeight) / 2;

    const popup = window.open(
      `/oauth-authorize.html?${authUrl.split('?')[1] || ''}`,
      'pn_oauth',
      `width=${popupWidth},height=${popupHeight},left=${left},top=${top},resizable=yes,scrollbars=yes`
    );

    if (!popup) {
      showError('Popup blocked. Please allow popups for this site.');
      return;
    }

    // Monitor popup for close (user might have cancelled)
    const checkClosed = setInterval(() => {
      if (popup.closed) {
        clearInterval(checkClosed);
      }
    }, 500);
  };

  // Don't show if already unlocked
  if (userState.isUnlocked && userState.pnIdentifier) {
    return null;
  }

  return (
    <>
      {compact ? (
        <button
          onClick={handleConnect}
          className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors"
        >
          <Lock className="h-4 w-4" />
          <span>Unlock pN</span>
        </button>
      ) : (
        <div className="bg-gradient-to-br from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-xl p-6 text-center">
          <Lock className="h-12 w-12 text-blue-400 mx-auto mb-4" />
          <h3 className="text-white text-xl font-bold mb-2">Connect Your pN to Engage</h3>
          <p className="text-text-secondary mb-6">
            Unlock likes, comments, and full interaction with the par Noir network
          </p>
          
          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="flex flex-col items-center space-y-2">
              <div className="w-12 h-12 bg-blue-500/20 rounded-full flex items-center justify-center">
                <Heart className="h-6 w-6 text-blue-400" />
              </div>
              <span className="text-xs text-text-secondary">Like Content</span>
            </div>
            <div className="flex flex-col items-center space-y-2">
              <div className="w-12 h-12 bg-blue-500/20 rounded-full flex items-center justify-center">
                <MessageCircle className="h-6 w-6 text-blue-400" />
              </div>
              <span className="text-xs text-text-secondary">Comment</span>
            </div>
            <div className="flex flex-col items-center space-y-2">
              <div className="w-12 h-12 bg-blue-500/20 rounded-full flex items-center justify-center">
                <Share2 className="h-6 w-6 text-blue-400" />
              </div>
              <span className="text-xs text-text-secondary">Share</span>
            </div>
          </div>
          
          <button
            onClick={handleConnect}
            className="px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
          >
            Unlock pN
          </button>
          
          <p className="text-xs text-text-secondary mt-4">
            Your pN gives you full control over your identity and data
          </p>
        </div>
      )}
    </>
  );
}

