/**
 * Google Drive Metadata Service (Client-Side)
 * Companion + owner/public indexes via par Noir API (Sheets / metadata-index).
 * No direct googleapis.com Drive or OAuth fetches from the dashboard client.
 */

import { API_ENDPOINT } from '../../config/api';
import { ownerFetch, ownerGet } from '../ownerApiService';
import { resolveOwnerApiToken } from '../ownerApiToken';

/**
 * Engagement Metrics (tracked in companion metadata)
 */
export interface EngagementMetrics {
  views: number;
  likes: number;
  comments: number;
  shares: number;
  saves?: number;
  lastUpdated: string;
  engagementHistory?: Array<{
    type: 'like' | 'comment' | 'share' | 'view' | 'save';
    did?: string; // Optional: who engaged (for analytics, privacy-preserving)
    timestamp: string;
  }>;
}

/**
 * Comprehensive Semantic Web Metadata
 * Supports schema.org, Dublin Core, PROV-O, FOAF, ActivityPub, and more
 */
export interface CompanionMetadata {
  // Core file information
  fileId: string;
  googleDriveFileId: string;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  visibility: 'private' | 'public' | 'friends';
  uploadedAt: string;
  owner: {
    did?: string;
    identifier: string;
  };
  
  // Basic metadata (user-editable)
  tags?: string[];
  geminiTags?: string[]; // Tags generated by Gemini AI (for provenance tracking)
  description?: string;
  metadata?: any;
  
  // Share token and thumbnail
  publicToken?: any; // Slim share token for public files (no shareEncrypted)
  publicContentRef?: {
    backend: string;
    objectId: string;
    publicUrl: string;
  };
  thumbnail?: string; // Base64 data URL or URL for thumbnail/preview
  thumbnailFileId?: string; // Reference to thumbnail file used in feeds
  mainFileId?: string; // Reference to main file (for thumbnails) - the main file is for owner download only

  // Indexing permissions for third-party catalogs
  indexingPermissions?: {
    mode?: 'all' | 'custom' | 'none';
    allowed?: string[];
    blocked?: string[];
    updatedAt?: string;
  };
  
  // ============================================================================
  // DUBLIN CORE METADATA (dc:)
  // ============================================================================
  dc?: {
    title?: string;
    creator?: string; // DID URI
    subject?: string[]; // Topics/subjects
    description?: string;
    publisher?: string; // DID URI
    contributor?: string[]; // DID URIs
    date?: string; // ISO 8601
    type?: string; // DCMI Type Vocabulary
    format?: string; // MIME type
    identifier?: string; // URI
    source?: string; // URI of source
    language?: string; // ISO 639-1 or RFC 5646
    relation?: string[]; // URIs of related resources
    coverage?: string; // Spatial/temporal coverage
    rights?: string; // License URI or text
    rightsHolder?: string; // DID URI
  };
  
  // ============================================================================
  // SCHEMA.ORG EXTENDED PROPERTIES
  // ============================================================================
  schema?: {
    // Temporal metadata
    dateCreated?: string; // ISO 8601
    dateModified?: string; // ISO 8601
    datePublished?: string; // ISO 8601
    copyrightYear?: number;
    expires?: string; // ISO 8601
    
    // Content classification
    genre?: string[]; // e.g., "photography", "art", "documentation"
    category?: string; // Main category
    about?: Array<{
      '@type': string; // e.g., "Thing", "Place", "Event"
      name: string;
      identifier?: string;
    }>;
    
    // Location/Place
    locationCreated?: {
      '@type': 'Place';
      name?: string;
      address?: {
        '@type': 'PostalAddress';
        addressLocality?: string;
        addressRegion?: string;
        addressCountry?: string;
      };
      geo?: {
        '@type': 'GeoCoordinates';
        latitude?: number;
        longitude?: number;
      };
    };
    
    // Technical metadata
    encodingFormat?: string; // MIME type
    fileSize?: number; // bytes
    contentSize?: string; // Human-readable
    
    // Media-specific (ImageObject, VideoObject, AudioObject)
    width?: number; // pixels
    height?: number; // pixels
    duration?: string; // ISO 8601 duration (e.g., "PT1M30S")
    bitrate?: number; // bits per second
    frameRate?: number; // frames per second
    audioSampleRate?: number; // Hz
    videoQuality?: string; // e.g., "1080p", "4K"
    
    // Rights and licensing
    license?: string | {
      '@type': 'CreativeWork';
      '@id': string; // License URI
      name: string;
    };
    copyrightHolder?: {
      '@type': 'Person' | 'Organization';
      '@id': string; // DID URI
      name?: string;
    };
    copyrightNotice?: string;
    usageInfo?: string; // Usage rights text
    
    // Accessibility
    accessibilityFeature?: string[]; // e.g., "captions", "audioDescription", "textAlternative"
    accessibilityHazard?: string[]; // e.g., "noFlashing", "noMotionSimulation"
    accessibilitySummary?: string;
    
    // Language
    inLanguage?: string | string[]; // ISO 639-1 or RFC 5646
    
    // Publishing
    publisher?: {
      '@type': 'Person' | 'Organization';
      '@id': string; // DID URI
      name?: string;
    };
    publishingPrinciples?: string; // URI
    
    // Creative work properties
    alternativeHeadline?: string;
    headline?: string;
    abstract?: string;
    text?: string; // Full text content (for documents)
    citation?: string | Array<{
      '@type': 'CreativeWork';
      '@id': string;
      name?: string;
    }>;
    
    // Collections and series
    isPartOf?: string | Array<{
      '@type': 'CreativeWorkSeries' | 'Collection';
      '@id': string;
      name?: string;
    }>;
    hasPart?: string[]; // URIs of parts
    
    // Ratings and reviews
    aggregateRating?: {
      '@type': 'AggregateRating';
      ratingValue: number;
      ratingCount: number;
      bestRating?: number;
      worstRating?: number;
    };
    
    // Comments and discussions
    commentCount?: number;
    
    // Keywords and topics
    keywords?: string[];
    subjectOf?: string; // URI of work about this resource
  };
  
  // ============================================================================
  // PROV-O (PROVENANCE)
  // ============================================================================
  prov?: {
    wasGeneratedBy?: {
      '@type': 'Activity';
      '@id': string; // Activity URI
      startedAtTime?: string; // ISO 8601
      endedAtTime?: string; // ISO 8601
      used?: string[]; // Resource URIs used in creation
    };
    wasAttributedTo?: string[]; // DID URIs of attributors
    wasDerivedFrom?: string[]; // URIs of source resources
    wasInfluencedBy?: string[]; // URIs of influencing resources
    hadPrimarySource?: string; // URI of primary source
    qualifiedDerivation?: Array<{
      '@type': 'Derivation';
      entity: string; // URI
      hadActivity?: string; // Activity URI
    }>;
  };
  
  // ============================================================================
  // FOAF (FRIEND OF A FRIEND) - Social Graph
  // ============================================================================
  foaf?: {
    maker?: string[]; // DID URIs of creators
    primaryTopic?: string; // URI of primary topic
    topic?: string[]; // URIs of topics
    depicts?: string[]; // URIs of things depicted
    thumbnail?: string; // Thumbnail URI
    homepage?: string; // Homepage URI
  };
  
  // ============================================================================
  // ACTIVITYPUB COMPATIBILITY
  // ============================================================================
  activitypub?: {
    '@context'?: string | string[];
    type?: string; // Activity type (Create, Update, Delete, etc.)
    actor?: string; // DID URI of actor
    object?: any; // Activity object (can be nested)
    target?: string; // Target URI
    to?: string[]; // Audience URIs
    cc?: string[]; // CC audience URIs
    published?: string; // ISO 8601
    updated?: string; // ISO 8601
    attachment?: Array<{
      type: string;
      mediaType: string;
      url: string;
      name?: string;
    }>;
    tag?: Array<{
      type: string;
      name: string;
      href?: string;
    }>;
    inReplyTo?: string; // URI
    content?: string; // HTML or plain text content
    summary?: string;
    sensitive?: boolean;
    replies?: {
      type: string;
      first?: {
        type: string;
        partOf: string;
        items: any[];
      };
    };
  };
  
  // ============================================================================
  // CONTENT RELATIONSHIPS (Simplified - maps to above)
  // ============================================================================
  inReplyTo?: string; // File ID of parent post/resource
  repostOf?: string; // File ID of original post/resource
  isPartOf?: string; // Curated feed identifier (creator DID)
  
  // ============================================================================
  // ENGAGEMENT METRICS
  // ============================================================================
  engagement?: EngagementMetrics;
}

export interface PublicFileIndex {
  identifier: string;
  files: Array<{
    fileId: string;
    googleDriveFileId: string;
    fileName: string;
    originalName: string;
    mimeType: string;
    size: number;
    visibility: string;
    uploadedAt: string;
    owner: {
      did?: string;
      identifier: string;
    };
    tags?: string[];
    description?: string;
    publicToken?: any;
    thumbnail?: string; // Base64 data URL or URL for thumbnail/preview
  }>;
  updatedAt: string;
}

/**
 * Client metadata facade: companion + indexes via par Noir API only.
 * Folder layout / Sheets companion writes happen server-side (storage initialize,
 * metadata-index PUT). No direct googleapis.com Drive/OAuth fetches.
 */
export class GoogleDriveMetadataService {
  /**
   * Create or update companion metadata via aggregator metadata-index.
   * API creates/updates Sheets companion under custody (X-PN-Cloud-Access-Token).
   * `_accessToken` retained for call-site compat; ignored (owner session token used).
   */
  static async createCompanionMetadataFile(
    _accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    const ownerToken = resolveOwnerApiToken(pnIdentifier);
    if (!ownerToken) {
      throw new Error('par Noir API session not ready');
    }
    const fileId = fileMetadata.googleDriveFileId || fileMetadata.fileId;
    if (!fileId) {
      throw new Error('Companion metadata requires googleDriveFileId or fileId');
    }
    const metaAny = fileMetadata as CompanionMetadata & Record<string, unknown>;
    const path = `/api/aggregator/metadata-index/${encodeURIComponent(fileId)}`;
    const res = await ownerFetch(
      ownerToken,
      'PUT',
      path,
      {
        name: fileMetadata.originalName || fileMetadata.fileName,
        description: fileMetadata.description || '',
        keywords: fileMetadata.tags || [],
        tags: fileMetadata.tags || [],
        isPublic: fileMetadata.visibility === 'public',
        publicToken: fileMetadata.publicToken,
        publicContentRef: fileMetadata.publicContentRef,
        fileType: (metaAny.fileType as string) || fileMetadata.mimeType?.split('/')[0] || 'other',
        uploadDate: fileMetadata.uploadedAt,
        thumbnailFileId: fileMetadata.thumbnailFileId ?? null,
        mainFileId: fileMetadata.mainFileId ?? null,
        textPost: metaAny.textPost ?? null,
        thought: metaAny.thought ?? null,
        collection: metaAny.collection ?? null,
        isThoughtThumbnail: metaAny.isThoughtThumbnail,
        isPartOfCollection: metaAny.isPartOfCollection,
        genre: fileMetadata.schema?.genre,
        category: fileMetadata.schema?.category,
        feedCategories: (fileMetadata.schema as { feedCategories?: string[] } | undefined)?.feedCategories,
        locationCreated: fileMetadata.schema?.locationCreated,
        license: fileMetadata.schema?.license,
        indexingPermissions: fileMetadata.indexingPermissions,
        engagement: fileMetadata.engagement,
      },
      { pnIdentifier }
    );
    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Failed to create/update companion metadata: ${res.status} ${err}`);
    }
  }

  /**
   * Folder / index file init is owned by POST /api/storage/initialize (server).
   * Kept as no-ops for any legacy callers.
   */
  static async initializeContentClassFolders(
    _accessToken: string,
    _metadataFolderId: string
  ): Promise<void> {
    /* no-op: API drive init */
  }

  static async initializeContentClassIndexFiles(
    _accessToken: string,
    _folderId: string,
    _folderName: string
  ): Promise<void> {
    /* no-op: API creates Sheets indexes on connect */
  }

  static async initializeIndexFiles(
    _accessToken: string,
    _metadataFolderId: string,
    _pnIdentifier: string
  ): Promise<void> {
    /* no-op: API creates owner/public index Sheets on connect */
  }

  /**
   * Get public file index (merged content-class + root) from the API (Sheets).
   */
  static async getPublicFileIndex(
    _accessToken: string,
    _metadataFolderId: string,
    pnIdentifier: string,
    _skipCleanup: boolean = false
  ): Promise<PublicFileIndex | null> {
    try {
      const res = await fetch(`${API_ENDPOINT}/api/storage/public-index/${encodeURIComponent(pnIdentifier)}`);
      if (!res.ok) return null;
      const data = await res.json();
      return {
        identifier: data.identifier ?? pnIdentifier,
        files: data.files ?? [],
        updatedAt: data.updatedAt ?? new Date().toISOString(),
      };
    } catch {
      return null;
    }
  }

  /**
   * Get owner file index (merged content-class + root) from the API (Sheets).
   * Under device custody the route may return 409; callers treat null as Drive listFiles.
   */
  static async getOwnerFileIndexFromContentClasses(
    pnIdentifier: string,
    ownerApiToken?: string | null
  ): Promise<PublicFileIndex | null> {
    return this.getOwnerFileIndex(pnIdentifier, ownerApiToken);
  }

  static async getOwnerFileIndex(
    pnIdentifier: string,
    ownerApiToken?: string | null
  ): Promise<PublicFileIndex | null> {
    try {
      const { isOwnerIndexUnavailable, markOwnerIndexUnavailable } = await import(
        './ownerIndexAvailability'
      );
      if (isOwnerIndexUnavailable(pnIdentifier)) {
        return null;
      }
      const path = `/api/storage/owner-index/${encodeURIComponent(pnIdentifier)}`;
      const res = ownerApiToken
        ? await ownerGet(ownerApiToken, path, { pnIdentifier })
        : await fetch(`${API_ENDPOINT}${path}`);
      if (res.status === 403 || res.status === 409) {
        markOwnerIndexUnavailable(pnIdentifier);
        return null;
      }
      if (!res.ok) return null;
      const data = await res.json();
      return {
        identifier: data.identifier ?? pnIdentifier,
        files: data.files ?? [],
        updatedAt: data.updatedAt ?? new Date().toISOString(),
      };
    } catch {
      return null;
    }
  }

  /**
   * Update owner file index via API (Sheets). `_accessToken` ignored.
   */
  static async updateOwnerFileIndex(
    _accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    const ownerToken = resolveOwnerApiToken(pnIdentifier);
    if (!ownerToken) {
      throw new Error('par Noir API session not ready');
    }
    const res = await ownerFetch(
      ownerToken,
      'POST',
      `/api/storage/owner-index/${encodeURIComponent(pnIdentifier)}/entries`,
      { entry: fileMetadata },
      { pnIdentifier }
    );
    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Failed to update owner index: ${res.status} ${err}`);
    }
  }

  /**
   * Update public file index via API (Sheets). `_accessToken` ignored.
   */
  static async updatePublicFileIndex(
    _accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    const ownerToken = resolveOwnerApiToken(pnIdentifier);
    if (!ownerToken) {
      throw new Error('par Noir API session not ready');
    }
    const res = await ownerFetch(
      ownerToken,
      'POST',
      `/api/storage/public-index/${encodeURIComponent(pnIdentifier)}/entries`,
      { entry: fileMetadata },
      { pnIdentifier }
    );
    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Failed to update public index: ${res.status} ${err}`);
    }
  }
}
