/**
 * Google Drive Metadata Service (Client-Side)
 * Creates companion metadata files and public indexing using Google Drive API directly
 */

/**
 * Engagement Metrics (tracked in companion metadata)
 */
export interface EngagementMetrics {
  views: number;
  likes: number;
  comments: number;
  shares: number;
  lastUpdated: string;
  engagementHistory?: Array<{
    type: 'like' | 'comment' | 'share' | 'view';
    did?: string; // Optional: who engaged (for analytics, privacy-preserving)
    timestamp: string;
  }>;
}

/**
 * Comprehensive Semantic Web Metadata
 * Supports schema.org, Dublin Core, PROV-O, FOAF, ActivityPub, and more
 */
export interface CompanionMetadata {
  // Core file information
  fileId: string;
  googleDriveFileId: string;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  visibility: 'private' | 'public' | 'friends';
  uploadedAt: string;
  owner: {
    did?: string;
    identifier: string;
  };
  
  // Basic metadata (user-editable)
  tags?: string[];
  geminiTags?: string[]; // Tags generated by Gemini AI (for provenance tracking)
  description?: string;
  metadata?: any;
  
  // Share token and thumbnail
  publicToken?: any; // Share token for public files (ShareToken object)
  thumbnail?: string; // Base64 data URL or URL for thumbnail/preview

  // Indexing permissions for third-party catalogs
  indexingPermissions?: {
    mode?: 'all' | 'custom' | 'none';
    allowed?: string[];
    blocked?: string[];
    updatedAt?: string;
  };
  
  // ============================================================================
  // DUBLIN CORE METADATA (dc:)
  // ============================================================================
  dc?: {
    title?: string;
    creator?: string; // DID URI
    subject?: string[]; // Topics/subjects
    description?: string;
    publisher?: string; // DID URI
    contributor?: string[]; // DID URIs
    date?: string; // ISO 8601
    type?: string; // DCMI Type Vocabulary
    format?: string; // MIME type
    identifier?: string; // URI
    source?: string; // URI of source
    language?: string; // ISO 639-1 or RFC 5646
    relation?: string[]; // URIs of related resources
    coverage?: string; // Spatial/temporal coverage
    rights?: string; // License URI or text
    rightsHolder?: string; // DID URI
  };
  
  // ============================================================================
  // SCHEMA.ORG EXTENDED PROPERTIES
  // ============================================================================
  schema?: {
    // Temporal metadata
    dateCreated?: string; // ISO 8601
    dateModified?: string; // ISO 8601
    datePublished?: string; // ISO 8601
    copyrightYear?: number;
    expires?: string; // ISO 8601
    
    // Content classification
    genre?: string[]; // e.g., "photography", "art", "documentation"
    category?: string; // Main category
    about?: Array<{
      '@type': string; // e.g., "Thing", "Place", "Event"
      name: string;
      identifier?: string;
    }>;
    
    // Location/Place
    locationCreated?: {
      '@type': 'Place';
      name?: string;
      address?: {
        '@type': 'PostalAddress';
        addressLocality?: string;
        addressRegion?: string;
        addressCountry?: string;
      };
      geo?: {
        '@type': 'GeoCoordinates';
        latitude?: number;
        longitude?: number;
      };
    };
    
    // Technical metadata
    encodingFormat?: string; // MIME type
    fileSize?: number; // bytes
    contentSize?: string; // Human-readable
    
    // Media-specific (ImageObject, VideoObject, AudioObject)
    width?: number; // pixels
    height?: number; // pixels
    duration?: string; // ISO 8601 duration (e.g., "PT1M30S")
    bitrate?: number; // bits per second
    frameRate?: number; // frames per second
    audioSampleRate?: number; // Hz
    videoQuality?: string; // e.g., "1080p", "4K"
    
    // Rights and licensing
    license?: string | {
      '@type': 'CreativeWork';
      '@id': string; // License URI
      name: string;
    };
    copyrightHolder?: {
      '@type': 'Person' | 'Organization';
      '@id': string; // DID URI
      name?: string;
    };
    copyrightNotice?: string;
    usageInfo?: string; // Usage rights text
    
    // Accessibility
    accessibilityFeature?: string[]; // e.g., "captions", "audioDescription", "textAlternative"
    accessibilityHazard?: string[]; // e.g., "noFlashing", "noMotionSimulation"
    accessibilitySummary?: string;
    
    // Language
    inLanguage?: string | string[]; // ISO 639-1 or RFC 5646
    
    // Publishing
    publisher?: {
      '@type': 'Person' | 'Organization';
      '@id': string; // DID URI
      name?: string;
    };
    publishingPrinciples?: string; // URI
    
    // Creative work properties
    alternativeHeadline?: string;
    headline?: string;
    abstract?: string;
    text?: string; // Full text content (for documents)
    citation?: string | Array<{
      '@type': 'CreativeWork';
      '@id': string;
      name?: string;
    }>;
    
    // Collections and series
    isPartOf?: string | Array<{
      '@type': 'CreativeWorkSeries' | 'Collection';
      '@id': string;
      name?: string;
    }>;
    hasPart?: string[]; // URIs of parts
    
    // Ratings and reviews
    aggregateRating?: {
      '@type': 'AggregateRating';
      ratingValue: number;
      ratingCount: number;
      bestRating?: number;
      worstRating?: number;
    };
    
    // Comments and discussions
    commentCount?: number;
    
    // Keywords and topics
    keywords?: string[];
    subjectOf?: string; // URI of work about this resource
  };
  
  // ============================================================================
  // PROV-O (PROVENANCE)
  // ============================================================================
  prov?: {
    wasGeneratedBy?: {
      '@type': 'Activity';
      '@id': string; // Activity URI
      startedAtTime?: string; // ISO 8601
      endedAtTime?: string; // ISO 8601
      used?: string[]; // Resource URIs used in creation
    };
    wasAttributedTo?: string[]; // DID URIs of attributors
    wasDerivedFrom?: string[]; // URIs of source resources
    wasInfluencedBy?: string[]; // URIs of influencing resources
    hadPrimarySource?: string; // URI of primary source
    qualifiedDerivation?: Array<{
      '@type': 'Derivation';
      entity: string; // URI
      hadActivity?: string; // Activity URI
    }>;
  };
  
  // ============================================================================
  // FOAF (FRIEND OF A FRIEND) - Social Graph
  // ============================================================================
  foaf?: {
    maker?: string[]; // DID URIs of creators
    primaryTopic?: string; // URI of primary topic
    topic?: string[]; // URIs of topics
    depicts?: string[]; // URIs of things depicted
    thumbnail?: string; // Thumbnail URI
    homepage?: string; // Homepage URI
  };
  
  // ============================================================================
  // ACTIVITYPUB COMPATIBILITY
  // ============================================================================
  activitypub?: {
    '@context'?: string | string[];
    type?: string; // Activity type (Create, Update, Delete, etc.)
    actor?: string; // DID URI of actor
    object?: any; // Activity object (can be nested)
    target?: string; // Target URI
    to?: string[]; // Audience URIs
    cc?: string[]; // CC audience URIs
    published?: string; // ISO 8601
    updated?: string; // ISO 8601
    attachment?: Array<{
      type: string;
      mediaType: string;
      url: string;
      name?: string;
    }>;
    tag?: Array<{
      type: string;
      name: string;
      href?: string;
    }>;
    inReplyTo?: string; // URI
    content?: string; // HTML or plain text content
    summary?: string;
    sensitive?: boolean;
    replies?: {
      type: string;
      first?: {
        type: string;
        partOf: string;
        items: any[];
      };
    };
  };
  
  // ============================================================================
  // CONTENT RELATIONSHIPS (Simplified - maps to above)
  // ============================================================================
  inReplyTo?: string; // File ID of parent post/resource
  repostOf?: string; // File ID of original post/resource
  isPartOf?: string; // Curated feed identifier (creator DID)
  
  // ============================================================================
  // ENGAGEMENT METRICS
  // ============================================================================
  engagement?: EngagementMetrics;
}

export interface PublicFileIndex {
  identifier: string;
  files: Array<{
    fileId: string;
    googleDriveFileId: string;
    fileName: string;
    originalName: string;
    mimeType: string;
    size: number;
    visibility: string;
    uploadedAt: string;
    owner: {
      did?: string;
      identifier: string;
    };
    tags?: string[];
    description?: string;
    publicToken?: any;
    thumbnail?: string; // Base64 data URL or URL for thumbnail/preview
  }>;
  updatedAt: string;
}

export class GoogleDriveMetadataService {
  private static readonly METADATA_FOLDER_NAME = '_metadata';
  private static readonly PUBLIC_INDEX_FILE_NAME = 'public-file-index.json';
  private static readonly OWNER_INDEX_FILE_NAME = 'owner-file-index.json';
  private static readonly PN_FOLDER_PREFIX = 'par Noir - pn-';
  
  /**
   * Standard semantic web contexts (comprehensive)
   */
  private static readonly SEMANTIC_CONTEXTS = [
    'https://schema.org/',
    'http://purl.org/dc/terms/',
    'http://www.w3.org/ns/prov#',
    'http://xmlns.com/foaf/0.1/',
    'https://www.w3.org/ns/activitystreams#',
    'https://parnoir.com/ns/v1#'
  ];
  
  /**
   * Generate resource URI for a file
   */
  private static generateResourceUri(fileId: string): string {
    return `https://parnoir.com/resource/${fileId}`;
  }
  
  /**
   * Ensure @context is always an array
   */
  private static ensureContextArray(context?: string | string[]): string[] {
    if (!context) {
      return this.SEMANTIC_CONTEXTS;
    }
    if (Array.isArray(context)) {
      return context;
    }
    return [context, ...this.SEMANTIC_CONTEXTS.filter(c => c !== context)];
  }
  
  /**
   * Convert CompanionMetadata to PublicMetadata (semantic web format)
   */
  private static companionToPublicMetadata(
    companion: CompanionMetadata,
    creatorDid?: string
  ): any {
    // Determine schema.org type from mime type
    const mimeCategory = companion.mimeType?.split('/')[0] || 'file';
    const schemaType = 
      mimeCategory === 'image' ? 'ImageObject' :
      mimeCategory === 'video' ? 'VideoObject' :
      mimeCategory === 'audio' ? 'AudioObject' :
      'CreativeWork';
    
    // Generate resource URI
    const resourceUri = this.generateResourceUri(companion.fileId);
    const didUri = creatorDid || companion.owner.did || `did:key:${companion.owner.identifier}`;
    
    // Build comprehensive public metadata with full semantic web structure
    const publicMetadata: any = {
      '@context': this.SEMANTIC_CONTEXTS,
      '@type': schemaType,
      '@id': resourceUri,
      
      // ============================================================================
      // CORE IDENTIFIERS
      // ============================================================================
      fileId: companion.fileId,
      backend: 'google_drive',
      backendFileId: companion.googleDriveFileId,
      
      // ============================================================================
      // SCHEMA.ORG CREATIVEWORK PROPERTIES
      // ============================================================================
      name: companion.originalName || companion.fileName,
      description: companion.description || '',
      keywords: companion.tags || [],
      uploadDate: companion.uploadedAt,
      datePublished: companion.uploadedAt,
      fileType: mimeCategory,
      
      // Creator (schema.org:creator)
      creator: {
        '@type': 'Person',
        '@id': didUri,
        identifier: {
          '@type': 'PropertyValue',
          name: 'DID',
          value: didUri
        }
      },
      
      // Legacy author support (for backward compatibility)
      author: {
        did: didUri
      },
      
      // ============================================================================
      // DUBLIN CORE METADATA (dc:)
      // ============================================================================
      ...(companion.dc && {
        'dc:title': companion.dc.title || companion.originalName || companion.fileName,
        'dc:creator': companion.dc.creator || didUri,
        'dc:subject': companion.dc.subject || companion.tags || [],
        'dc:description': companion.dc.description || companion.description || '',
        'dc:publisher': companion.dc.publisher || didUri,
        'dc:contributor': companion.dc.contributor || [],
        'dc:date': companion.dc.date || companion.uploadedAt,
        'dc:type': companion.dc.type || schemaType,
        'dc:format': companion.dc.format || companion.mimeType,
        'dc:identifier': companion.dc.identifier || resourceUri,
        'dc:source': companion.dc.source,
        'dc:language': companion.dc.language,
        'dc:relation': companion.dc.relation || [],
        'dc:coverage': companion.dc.coverage,
        'dc:rights': companion.dc.rights,
        'dc:rightsHolder': companion.dc.rightsHolder || didUri
      }),
      
      // ============================================================================
      // SCHEMA.ORG EXTENDED PROPERTIES
      // ============================================================================
      ...(companion.schema && {
        // Temporal metadata
        dateCreated: companion.schema.dateCreated || companion.uploadedAt,
        dateModified: companion.schema.dateModified || companion.uploadedAt,
        datePublished: companion.schema.datePublished || companion.uploadedAt,
        copyrightYear: companion.schema.copyrightYear,
        expires: companion.schema.expires,
        
        // Content classification
        genre: companion.schema.genre || [],
        category: companion.schema.category,
        about: companion.schema.about || [],
        
        // Location
        locationCreated: companion.schema.locationCreated,
        
        // Technical metadata
        encodingFormat: companion.schema.encodingFormat || companion.mimeType,
        fileSize: companion.schema.fileSize || companion.size,
        contentSize: companion.schema.contentSize,
        
        // Media-specific
        width: companion.schema.width,
        height: companion.schema.height,
        duration: companion.schema.duration,
        bitrate: companion.schema.bitrate,
        frameRate: companion.schema.frameRate,
        audioSampleRate: companion.schema.audioSampleRate,
        videoQuality: companion.schema.videoQuality,
        
        // Rights and licensing
        license: companion.schema.license,
        copyrightHolder: companion.schema.copyrightHolder,
        copyrightNotice: companion.schema.copyrightNotice,
        usageInfo: companion.schema.usageInfo,
        
        // Accessibility
        accessibilityFeature: companion.schema.accessibilityFeature || [],
        accessibilityHazard: companion.schema.accessibilityHazard || [],
        accessibilitySummary: companion.schema.accessibilitySummary,
        
        // Language
        inLanguage: companion.schema.inLanguage,
        
        // Publishing
        publisher: companion.schema.publisher,
        publishingPrinciples: companion.schema.publishingPrinciples,
        
        // Creative work properties
        alternativeHeadline: companion.schema.alternativeHeadline,
        headline: companion.schema.headline,
        abstract: companion.schema.abstract,
        text: companion.schema.text,
        citation: companion.schema.citation,
        
        // Collections
        isPartOf: companion.schema.isPartOf || (companion.isPartOf ? `https://parnoir.com/curated/${companion.isPartOf}` : undefined),
        hasPart: companion.schema.hasPart || [],
        
        // Ratings
        aggregateRating: companion.schema.aggregateRating,
        
        // Comments
        commentCount: companion.schema.commentCount || companion.engagement?.comments || 0,
        
        // Keywords (merge with tags)
        keywords: [...(companion.schema.keywords || []), ...(companion.tags || [])],
        subjectOf: companion.schema.subjectOf
      }),
      
      // ============================================================================
      // PROV-O (PROVENANCE)
      // ============================================================================
      ...(companion.prov && {
        'prov:wasGeneratedBy': companion.prov.wasGeneratedBy,
        'prov:wasAttributedTo': companion.prov.wasAttributedTo || [didUri],
        'prov:wasDerivedFrom': companion.prov.wasDerivedFrom || [],
        'prov:wasInfluencedBy': companion.prov.wasInfluencedBy || [],
        'prov:hadPrimarySource': companion.prov.hadPrimarySource,
        'prov:qualifiedDerivation': companion.prov.qualifiedDerivation || []
      }),
      
      // ============================================================================
      // FOAF (FRIEND OF A FRIEND)
      // ============================================================================
      ...(companion.foaf && {
        'foaf:maker': companion.foaf.maker || [didUri],
        'foaf:primaryTopic': companion.foaf.primaryTopic,
        'foaf:topic': companion.foaf.topic || [],
        'foaf:depicts': companion.foaf.depicts || [],
        'foaf:thumbnail': companion.foaf.thumbnail || (companion.thumbnail ? `${resourceUri}/thumbnail` : undefined),
        'foaf:homepage': companion.foaf.homepage
      }),
      
      // ============================================================================
      // ACTIVITYPUB COMPATIBILITY
      // ============================================================================
      ...(companion.activitypub && {
        'as:type': companion.activitypub.type || 'Create',
        'as:actor': companion.activitypub.actor || didUri,
        'as:object': companion.activitypub.object,
        'as:target': companion.activitypub.target,
        'as:to': companion.activitypub.to || ['https://www.w3.org/ns/activitystreams#Public'],
        'as:cc': companion.activitypub.cc || [],
        'as:published': companion.activitypub.published || companion.uploadedAt,
        'as:updated': companion.activitypub.updated || companion.uploadedAt,
        'as:attachment': companion.activitypub.attachment || [],
        'as:tag': companion.activitypub.tag || (companion.tags?.map(tag => ({ type: 'Hashtag', name: tag })) || []),
        'as:inReplyTo': companion.activitypub.inReplyTo || (companion.inReplyTo ? this.generateResourceUri(companion.inReplyTo) : undefined),
        'as:content': companion.activitypub.content || companion.description || '',
        'as:summary': companion.activitypub.summary,
        'as:sensitive': companion.activitypub.sensitive || false,
        'as:replies': companion.activitypub.replies
      }),
      
      // ============================================================================
      // MEDIA PROPERTIES
      // ============================================================================
      thumbnail: companion.thumbnail ? {
        '@type': 'ImageObject',
        '@id': `${resourceUri}/thumbnail`,
        'foaf:thumbnail': `${resourceUri}/thumbnail`
      } : undefined,

      // Third-party indexing permissions
      indexingPermissions: companion.indexingPermissions,
      
      // ============================================================================
      // CONTENT RELATIONSHIPS
      // ============================================================================
      inReplyTo: companion.inReplyTo ? this.generateResourceUri(companion.inReplyTo) : undefined,
      repostOf: companion.repostOf ? this.generateResourceUri(companion.repostOf) : undefined,
      isPartOf: companion.isPartOf ? `https://parnoir.com/curated/${companion.isPartOf}` : undefined,
      
      // ============================================================================
      // ENGAGEMENT METRICS (always include, initialize if not present)
      // ============================================================================
      engagement: {
        views: companion.engagement?.views || 0,
        likes: companion.engagement?.likes || 0,
        comments: companion.engagement?.comments || 0,
        shares: companion.engagement?.shares || 0,
        lastUpdated: companion.engagement?.lastUpdated || companion.uploadedAt,
        engagementHistory: companion.engagement?.engagementHistory || []
      },
      
      // ============================================================================
      // PAR NOIR SPECIFIC
      // ============================================================================
      publicToken: companion.publicToken,
      isPublic: companion.visibility === 'public',
      
      // Additional semantic relationships
      sameAs: companion.metadata?.sameAs || [],
      about: companion.metadata?.about || []
    };
    
    // Remove undefined fields
    Object.keys(publicMetadata).forEach(key => {
      if (publicMetadata[key] === undefined || 
          (Array.isArray(publicMetadata[key]) && publicMetadata[key].length === 0 && !key.includes(':'))) {
        delete publicMetadata[key];
      }
    });
    
    return publicMetadata;
  }
  
  /**
   * Get service account email for sharing folders
   * This allows the API server to scan Google Drive for public files
   */
  private static getServiceAccountEmail(): string | null {
    // Try to get from environment variable (set at build time)
    const serviceAccountKey = import.meta.env.VITE_GOOGLE_SERVICE_ACCOUNT_KEY;
    if (serviceAccountKey) {
      try {
        const key = typeof serviceAccountKey === 'string' ? JSON.parse(serviceAccountKey) : serviceAccountKey;
        return key.client_email || null;
      } catch {
        // If parsing fails, try direct email env var
        return import.meta.env.VITE_GOOGLE_SERVICE_ACCOUNT_EMAIL || null;
      }
    }
    // Fallback to direct email env var
    return import.meta.env.VITE_GOOGLE_SERVICE_ACCOUNT_EMAIL || null;
  }

  /**
   * Share folder with service account (for API server scanning)
   */
  private static async shareFolderWithServiceAccount(
    accessToken: string,
    folderId: string
  ): Promise<void> {
    const serviceAccountEmail = this.getServiceAccountEmail();
    
    if (!serviceAccountEmail) {
      // Service account not configured - this is okay, just skip sharing
      console.log('ℹ️ Service account email not configured - skipping folder sharing');
      return;
    }

    try {
      // Check if permission already exists
      const permissionsResponse = await fetch(
        `https://www.googleapis.com/drive/v3/files/${folderId}/permissions?fields=permissions(emailAddress)`,
        {
          headers: {
            'Authorization': `Bearer ${accessToken}`
          }
        }
      );

      if (permissionsResponse.ok) {
        const permissionsData = await permissionsResponse.json();
        const hasPermission = permissionsData.permissions?.some(
          (p: any) => p.emailAddress === serviceAccountEmail
        );
        
        if (hasPermission) {
          console.log('✅ Folder already shared with service account');
          return;
        }
      }

      // Share folder with service account
      const shareResponse = await fetch(
        `https://www.googleapis.com/drive/v3/files/${folderId}/permissions`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            role: 'reader',
            type: 'user',
            emailAddress: serviceAccountEmail
          })
        }
      );

      if (shareResponse.ok) {
        console.log(`✅ Shared folder with service account: ${serviceAccountEmail}`);
      } else {
        const errorText = await shareResponse.text();
        console.warn(`⚠️ Failed to share folder with service account: ${shareResponse.status} - ${errorText}`);
        // Don't throw - this is not critical, just log a warning
      }
    } catch (error) {
      console.warn('⚠️ Error sharing folder with service account:', error);
      // Don't throw - this is not critical for the main operation
    }
  }

  /**
   * Get or create the pN folder structure
   */
  static async getOrCreatePNFolder(
    accessToken: string,
    pnIdentifier: string
  ): Promise<string> {
    // Strip 'pn-' prefix if it exists (pnIdentifier might already include it)
    const cleanIdentifier = pnIdentifier.startsWith('pn-') 
      ? pnIdentifier.substring(3) 
      : pnIdentifier;
    const folderName = `${this.PN_FOLDER_PREFIX}${cleanIdentifier}`;
    
    // Search for existing folder
    const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${encodeURIComponent(folderName)}' and mimeType='application/vnd.google-apps.folder' and trashed=false&fields=files(id,name)`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!searchResponse.ok) {
      // Handle expired/invalid token gracefully
      if (searchResponse.status === 401 || searchResponse.status === 403) {
        throw new Error(`Token expired or invalid (${searchResponse.status}) - cannot access Google Drive folders`);
      }
      throw new Error(`Failed to search for pN folder: ${searchResponse.status} ${searchResponse.statusText}`);
    }

    const searchData = await searchResponse.json();
    
    if (searchData.files && searchData.files.length > 0) {
      return searchData.files[0].id;
    }

    // Create new folder
    const createResponse = await fetch(
      'https://www.googleapis.com/drive/v3/files',
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: folderName,
          mimeType: 'application/vnd.google-apps.folder'
        })
      }
    );

    if (!createResponse.ok) {
      throw new Error('Failed to create pN folder');
    }

    const folderData = await createResponse.json();
    return folderData.id;
  }

  /**
   * Get or create the _metadata folder
   */
  static async getOrCreateMetadataFolder(
    accessToken: string,
    pnFolderId: string
  ): Promise<string> {
    // Search for existing _metadata folder
    const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${this.METADATA_FOLDER_NAME}' and '${pnFolderId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false&fields=files(id,name)`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!searchResponse.ok) {
      throw new Error('Failed to search for metadata folder');
    }

    const searchData = await searchResponse.json();
    
    if (searchData.files && searchData.files.length > 0) {
      return searchData.files[0].id;
    }

    // Create new _metadata folder
    const createResponse = await fetch(
      'https://www.googleapis.com/drive/v3/files',
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: this.METADATA_FOLDER_NAME,
          mimeType: 'application/vnd.google-apps.folder',
          parents: [pnFolderId]
        })
      }
    );

    if (!createResponse.ok) {
      throw new Error('Failed to create metadata folder');
    }

    const folderData = await createResponse.json();
    return folderData.id;
  }

  /**
   * Initialize all content class folders (media, thoughts, collections)
   * This ensures the folder structure exists before any files are uploaded
   */
  static async initializeContentClassFolders(
    accessToken: string,
    metadataFolderId: string
  ): Promise<void> {
    const contentClassFolders = ['media', 'thoughts', 'collections'];
    
    for (const folderName of contentClassFolders) {
      try {
        // Check if folder already exists
        const folderQuery = `name='${folderName}' and '${metadataFolderId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`;
        const searchUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(folderQuery)}&fields=files(id)&pageSize=1`;
        const searchResponse = await fetch(searchUrl, {
          headers: { 'Authorization': `Bearer ${accessToken}` }
        });

        if (searchResponse.ok) {
          const searchData = await searchResponse.json() as { files?: Array<{ id: string }> };
          if (searchData.files && searchData.files.length > 0) {
            console.log(`[GoogleDriveMetadataService] Folder '${folderName}' already exists`);
            continue;
          }
        }

        // Create folder if it doesn't exist
        const createResponse = await fetch('https://www.googleapis.com/drive/v3/files', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            name: folderName,
            mimeType: 'application/vnd.google-apps.folder',
            parents: [metadataFolderId]
          })
        });

        if (createResponse.ok) {
          const folderData = await createResponse.json() as { id: string };
          console.log(`[GoogleDriveMetadataService] Created folder '${folderName}' (ID: ${folderData.id})`);
        } else {
          const errorText = await createResponse.text();
          console.warn(`[GoogleDriveMetadataService] Failed to create folder '${folderName}': ${createResponse.status} ${errorText}`);
        }
      } catch (error: any) {
        console.error(`[GoogleDriveMetadataService] Error creating folder '${folderName}':`, error);
        // Don't throw - continue with other folders
      }
    }
  }

  /**
   * Create or update companion metadata file
   */
  static async createCompanionMetadataFile(
    accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    try {
      console.log('Creating companion metadata file for:', fileMetadata.googleDriveFileId);
      
      // Get or create folder structure
      // Get or create pN folder (pN identifier is secret - not logged)
      const pnFolderId = await this.getOrCreatePNFolder(accessToken, pnIdentifier);
      
      console.log('Getting/creating metadata folder');
      const metadataFolderId = await this.getOrCreateMetadataFolder(accessToken, pnFolderId);
      console.log('Metadata folder ID:', metadataFolderId);

      // Initialize all content class folders if this is a new metadata folder
      await this.initializeContentClassFolders(accessToken, metadataFolderId);

      // Determine contentClass from metadata
      // Use same logic as server-side determineContentClass utility for consistency
      let contentClass = fileMetadata.contentClass;
      if (!contentClass) {
        const metadataAny = fileMetadata as any;
        // Collection takes precedence
        if (metadataAny.collection?.collectionFileIds?.length) {
          contentClass = 'collection';
        }
        // Thought (including thumbnails) - CRITICAL: isThoughtThumbnail must be checked
        else if (metadataAny.isThoughtThumbnail || metadataAny.thought || metadataAny.textPost) {
          contentClass = 'thought';
        }
        // Default to media for everything else
        // fileType is NOT checked - contentClass is for feed filtering, not technical file type
        else {
          contentClass = 'media';
        }
      }

      // Get or create content type subfolder
      const contentTypeFolderName = contentClass === 'thought' ? 'thoughts' : contentClass; // Map 'thought' to 'thoughts' folder
      const contentTypeFolderQuery = `name='${contentTypeFolderName}' and '${metadataFolderId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`;
      const contentTypeFolderResponse = await fetch(
        `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(contentTypeFolderQuery)}&fields=files(id,name)&pageSize=1`,
        {
          headers: {
            'Authorization': `Bearer ${accessToken}`
          }
        }
      );

      let contentTypeFolderId: string;
      if (contentTypeFolderResponse.ok) {
        const contentTypeFolderData = await contentTypeFolderResponse.json();
        if (contentTypeFolderData.files && contentTypeFolderData.files.length > 0) {
          contentTypeFolderId = contentTypeFolderData.files[0].id;
        } else {
          // Create subfolder
          const createFolderResponse = await fetch(
            'https://www.googleapis.com/drive/v3/files',
            {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                name: contentTypeFolderName,
                mimeType: 'application/vnd.google-apps.folder',
                parents: [metadataFolderId]
              })
            }
          );
          if (!createFolderResponse.ok) {
            throw new Error('Failed to create content type subfolder');
          }
          const folderData = await createFolderResponse.json();
          contentTypeFolderId = folderData.id;
        }
      } else {
        throw new Error('Failed to search for content type subfolder');
      }

      const metadataFileName = `${fileMetadata.googleDriveFileId}.metadata.json`;
      
      // Check if metadata file already exists in the subfolder
      const searchResponse = await fetch(
        `https://www.googleapis.com/drive/v3/files?q=name='${encodeURIComponent(metadataFileName)}' and '${contentTypeFolderId}' in parents and trashed=false&fields=files(id)`,
        {
          headers: {
            'Authorization': `Bearer ${accessToken}`
          }
        }
      );

      if (!searchResponse.ok) {
        throw new Error('Failed to search for existing metadata file');
      }

      const searchData = await searchResponse.json();
      const metadataContent = JSON.stringify(fileMetadata, null, 2);
      const metadataBlob = new Blob([metadataContent], { type: 'application/json' });

      if (searchData.files && searchData.files.length > 0) {
        // Update existing metadata file
        const fileId = searchData.files[0].id;
        
        // Get current metadata to check if we need to update
        try {
          const getResponse = await fetch(
            `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
            {
              headers: {
                'Authorization': `Bearer ${accessToken}`
              }
            }
          );

          if (getResponse.ok) {
            const existingMetadataText = await getResponse.text();
            try {
              const existingMetadata = JSON.parse(existingMetadataText) as CompanionMetadata;
              // Merge with new metadata, preserving existing fields
              if (existingMetadata.publicToken) {
                (fileMetadata as any).publicToken = existingMetadata.publicToken;
              }
              // Preserve engagement metrics if they exist
              if (existingMetadata.engagement) {
                fileMetadata.engagement = existingMetadata.engagement;
              }
              // Preserve relationships if they exist
              if (existingMetadata.inReplyTo) {
                fileMetadata.inReplyTo = existingMetadata.inReplyTo;
              }
              if (existingMetadata.repostOf) {
                fileMetadata.repostOf = existingMetadata.repostOf;
              }
              if (existingMetadata.isPartOf) {
                fileMetadata.isPartOf = existingMetadata.isPartOf;
              }
              if (existingMetadata.indexingPermissions && !fileMetadata.indexingPermissions) {
                fileMetadata.indexingPermissions = existingMetadata.indexingPermissions;
              }
            } catch (parseError) {
              console.warn('Failed to parse existing metadata, continuing with new metadata');
            }
          }
        } catch (getError) {
          console.warn('Failed to get existing metadata, continuing with new metadata:', getError);
        }

        // Update file content (JSON) using media upload (avoids multipart issues)
        const updateResponse = await fetch(
          `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`,
          {
            method: 'PATCH',
            headers: {
              'Authorization': `Bearer ${accessToken}`,
              'Content-Type': 'application/json; charset=UTF-8'
            },
            body: JSON.stringify(fileMetadata)
          }
        );

        if (!updateResponse.ok) {
          const errorText = await updateResponse.text();
          console.error('Failed to update companion metadata file:', {
            status: updateResponse.status,
            statusText: updateResponse.statusText,
            errorText
          });
          throw new Error('Failed to update metadata file');
        }
      } else {
        // Create new metadata file
        const formData = new FormData();
        formData.append('metadata', new Blob([JSON.stringify({
          name: metadataFileName,
          parents: [contentTypeFolderId]
        })], { type: 'application/json' }));
        formData.append('file', metadataBlob);

        const createResponse = await fetch(
          'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',
          {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${accessToken}`
            },
            body: formData
          }
        );

        if (!createResponse.ok) {
          const errorText = await createResponse.text();
          console.error('Failed to create metadata file. Status:', createResponse.status, 'StatusText:', createResponse.statusText);
          console.error('Error response:', errorText);
          throw new Error(`Failed to create metadata file: ${createResponse.status} ${createResponse.statusText}. ${errorText}`);
        }
        
        console.log('✅ Metadata file created successfully');
      }
    } catch (error) {
      console.error('Error creating companion metadata file:', error);
      throw error;
    }
  }

  /**
   * Get or create public file index
   */
  static async getPublicFileIndex(
    accessToken: string,
    metadataFolderId: string,
    pnIdentifier: string,
    skipCleanup: boolean = false
  ): Promise<PublicFileIndex | null> {
    const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${this.PUBLIC_INDEX_FILE_NAME}' and '${metadataFolderId}' in parents and trashed=false&fields=files(id)`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!searchResponse.ok) {
      return null;
    }

    const searchData = await searchResponse.json();
    
    if (!searchData.files || searchData.files.length === 0) {
      return null;
    }

    // Download existing index
    const fileId = searchData.files[0].id;
    const getResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!getResponse.ok) {
      return null;
    }

    let index: PublicFileIndex;
    try {
      index = await getResponse.json();
    } catch {
      return {
        identifier: pnIdentifier,
        files: [],
        updatedAt: new Date().toISOString()
      };
    }

    // REMOVED AUTOMATIC CLEANUP: getPublicFileIndex is now read-only
    // Cleanup should be done explicitly via cleanupOrphanedIndexEntries or a dedicated cleanup endpoint
    // This prevents files from being removed incorrectly during normal reads

    return index;
  }

  /**
   * Get owner file index (contains all files owned by the user)
   */
  static async getOwnerFileIndex(
    accessToken: string,
    metadataFolderId: string,
    pnIdentifier: string
  ): Promise<PublicFileIndex | null> {
    const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${this.OWNER_INDEX_FILE_NAME}' and '${metadataFolderId}' in parents and trashed=false&fields=files(id)`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!searchResponse.ok) {
      return null;
    }

    const searchData = await searchResponse.json();
    
    if (!searchData.files || searchData.files.length === 0) {
      return null;
    }

    // Download existing index
    const fileId = searchData.files[0].id;
    const getResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    if (!getResponse.ok) {
      return null;
    }

    let index: PublicFileIndex;
    try {
      index = await getResponse.json();
    } catch {
      return {
        identifier: pnIdentifier,
        files: [],
        updatedAt: new Date().toISOString()
      };
    }

    // AUTOMATIC CLEANUP: Verify files exist and remove orphaned entries
    // Google Drive is the source of truth - if file doesn't exist, remove from index
    if (index && index.files && index.files.length > 0) {
      const originalCount = index.files.length;
      const verifiedFiles = [];

      for (const fileEntry of index.files) {
        const googleDriveFileId = fileEntry.googleDriveFileId;
        if (googleDriveFileId) {
          const exists = await this.verifyFileExists(accessToken, googleDriveFileId);
          if (exists) {
            verifiedFiles.push(fileEntry);
          } else {
            console.log(`🗑️ [getOwnerFileIndex] Auto-removing orphaned file: ${googleDriveFileId} (${(fileEntry as any).fileName || (fileEntry as any).originalName || 'unknown'})`);
          }
        } else {
          // Keep entries without googleDriveFileId (might be from other backends)
          verifiedFiles.push(fileEntry);
        }
      }

      // If we removed any orphaned entries, update the index file
      if (verifiedFiles.length !== originalCount) {
        index.files = verifiedFiles;
        index.updatedAt = new Date().toISOString();
        await this.saveIndexFile(accessToken, metadataFolderId, this.OWNER_INDEX_FILE_NAME, index);
        console.log(`✅ [getOwnerFileIndex] Auto-cleaned index: removed ${originalCount - verifiedFiles.length} orphaned file(s)`);
      }
    }

    return index;
  }

  /**
   * Update owner file index (includes ALL files, regardless of visibility)
   */
  static async updateOwnerFileIndex(
    accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    try {
      const pnFolderId = await this.getOrCreatePNFolder(accessToken, pnIdentifier);
      const metadataFolderId = await this.getOrCreateMetadataFolder(accessToken, pnFolderId);

      let index = await this.getOwnerFileIndex(accessToken, metadataFolderId, pnIdentifier);
      
      if (!index) {
        index = {
          identifier: pnIdentifier,
          files: [],
          updatedAt: new Date().toISOString()
        };
      }

      // Convert companion metadata to index entry format (includes thumbnails)
      const indexEntry: any = {
        fileId: fileMetadata.fileId,
        googleDriveFileId: fileMetadata.googleDriveFileId,
        fileName: fileMetadata.fileName,
        originalName: fileMetadata.originalName,
        mimeType: fileMetadata.mimeType,
        size: fileMetadata.size,
        visibility: fileMetadata.visibility,
        uploadedAt: fileMetadata.uploadedAt,
        owner: fileMetadata.owner,
        tags: fileMetadata.tags || [],
        description: fileMetadata.description,
        thumbnail: fileMetadata.thumbnail, // Include thumbnail for owner access
        publicToken: fileMetadata.publicToken,
        engagement: fileMetadata.engagement,
        inReplyTo: fileMetadata.inReplyTo,
        repostOf: fileMetadata.repostOf,
        isPartOf: fileMetadata.isPartOf,
        indexingPermissions: fileMetadata.indexingPermissions
      };

      // Update or add file entry (all files go in owner index)
      const fileIndex = index.files.findIndex(
        f => f.googleDriveFileId === fileMetadata.googleDriveFileId
      );

      if (fileIndex >= 0) {
        // Update existing entry
        const existingEntry = index.files[fileIndex] as any;
        
        // Preserve publicToken if new one not provided
        if (!indexEntry.publicToken && existingEntry.publicToken) {
          indexEntry.publicToken = existingEntry.publicToken;
        }
        
        // Merge engagement metrics
        if (existingEntry.engagement) {
          indexEntry.engagement = {
            views: indexEntry.engagement?.views ?? existingEntry.engagement.views ?? 0,
            likes: indexEntry.engagement?.likes ?? existingEntry.engagement.likes ?? 0,
            comments: indexEntry.engagement?.comments ?? existingEntry.engagement.comments ?? 0,
            shares: indexEntry.engagement?.shares ?? existingEntry.engagement.shares ?? 0,
            lastUpdated: indexEntry.engagement?.lastUpdated || existingEntry.engagement.lastUpdated || fileMetadata.uploadedAt,
            engagementHistory: [
              ...(existingEntry.engagement.engagementHistory || []),
              ...(indexEntry.engagement?.engagementHistory || [])
            ]
          };
        }
        
        index.files[fileIndex] = indexEntry;
      } else {
        // Add new file to owner index
        index.files.push(indexEntry);
      }

      index.updatedAt = new Date().toISOString();

      // Save owner index file using helper method
      await this.saveIndexFile(accessToken, metadataFolderId, this.OWNER_INDEX_FILE_NAME, index);
      console.log(`✅ Updated owner file index`);
    } catch (error) {
      console.error('Error updating owner file index:', error);
      throw error;
    }
  }

  /**
   * Update public file index
   */
  static async updatePublicFileIndex(
    accessToken: string,
    pnIdentifier: string,
    fileMetadata: CompanionMetadata
  ): Promise<void> {
    try {
      const pnFolderId = await this.getOrCreatePNFolder(accessToken, pnIdentifier);
      const metadataFolderId = await this.getOrCreateMetadataFolder(accessToken, pnFolderId);

      // Skip cleanup when updating - we're adding/updating a file, so don't remove it
      let index = await this.getPublicFileIndex(accessToken, metadataFolderId, pnIdentifier, true);
      
      if (!index) {
        index = {
          identifier: pnIdentifier,
          files: [],
          updatedAt: new Date().toISOString()
        };
      }

      // Update or add file entry
      const fileIndex = index.files.findIndex(
        f => f.googleDriveFileId === fileMetadata.googleDriveFileId
      );

      if (fileMetadata.visibility === 'public') {
        // Convert companion metadata to public metadata (semantic web format)
        const publicMetadata = this.companionToPublicMetadata(
          fileMetadata,
          fileMetadata.owner.did
        );
        
        // Create index entry with full semantic metadata
        const indexEntry: any = {
          ...publicMetadata,
          // Keep legacy fields for compatibility with existing index structure
          fileId: fileMetadata.fileId,
          googleDriveFileId: fileMetadata.googleDriveFileId,
          fileName: fileMetadata.fileName,
          originalName: fileMetadata.originalName,
          mimeType: fileMetadata.mimeType,
          size: fileMetadata.size,
          visibility: fileMetadata.visibility,
          uploadedAt: fileMetadata.uploadedAt,
          owner: fileMetadata.owner,
          tags: fileMetadata.tags || [],
          description: fileMetadata.description,
          thumbnail: fileMetadata.thumbnail,
          publicToken: fileMetadata.publicToken,
          indexingPermissions: fileMetadata.indexingPermissions
        };

        const isNewPublicFile = fileIndex < 0;
        
        if (fileIndex >= 0) {
          // Update existing entry, preserve fields if new ones not provided
          const existingEntry = index.files[fileIndex] as any;
          
          // Preserve publicToken if new one not provided
          if (!indexEntry.publicToken && existingEntry.publicToken) {
            indexEntry.publicToken = existingEntry.publicToken;
          }
          
          // Merge engagement metrics (preserve existing engagement data)
          if (existingEntry.engagement) {
            // Merge: use existing engagement values, but allow new ones to override if provided
            indexEntry.engagement = {
              views: indexEntry.engagement?.views ?? existingEntry.engagement.views ?? 0,
              likes: indexEntry.engagement?.likes ?? existingEntry.engagement.likes ?? 0,
              comments: indexEntry.engagement?.comments ?? existingEntry.engagement.comments ?? 0,
              shares: indexEntry.engagement?.shares ?? existingEntry.engagement.shares ?? 0,
              lastUpdated: indexEntry.engagement?.lastUpdated || existingEntry.engagement.lastUpdated || fileMetadata.uploadedAt,
              // Preserve engagement history (append new events if any)
              engagementHistory: [
                ...(existingEntry.engagement.engagementHistory || []),
                ...(indexEntry.engagement?.engagementHistory || [])
              ]
            };
          }
          // If no existing engagement, use the new one (already set from companionToPublicMetadata)
          
          index.files[fileIndex] = indexEntry;
        } else {
          // Only add to index if public
          index.files.push(indexEntry);
        }

        // Share folder with service account when file becomes public (first time only)
        if (isNewPublicFile) {
          await this.shareFolderWithServiceAccount(accessToken, pnFolderId);
        }
      } else {
        // Remove from index if not public (should not be in index, but clean up just in case)
        if (fileIndex >= 0) {
          console.log(`Removing file ${fileMetadata.googleDriveFileId} from public index (visibility: ${fileMetadata.visibility})`);
          index.files.splice(fileIndex, 1);
        }
      }

      index.updatedAt = new Date().toISOString();

      // Save index file
      await this.saveIndexFile(accessToken, metadataFolderId, this.PUBLIC_INDEX_FILE_NAME, index);
    } catch (error) {
      console.error('Failed to update public file index:', error);
      throw error;
    }
  }

  /**
   * Verify if a file exists in Google Drive
   */
  private static async verifyFileExists(
    accessToken: string,
    fileId: string
  ): Promise<boolean> {
    try {
      const response = await fetch(
        `https://www.googleapis.com/drive/v3/files/${fileId}?fields=id,trashed`,
        {
          headers: {
            'Authorization': `Bearer ${accessToken}`
          }
        }
      );

      if (response.status === 404) {
        console.log(`🗑️ [verifyFileExists] File ${fileId} not found (404)`);
        return false; // File doesn't exist
      }

      if (!response.ok) {
        // If we can't verify (e.g., 401), assume file exists to avoid false positives
        console.warn(`⚠️ [verifyFileExists] Could not verify file ${fileId}: ${response.status}`);
        return true;
      }

      const fileData = await response.json();
      // File exists and is not trashed
      const exists = !fileData.trashed;
      if (!exists) {
        console.log(`🗑️ [verifyFileExists] File ${fileId} is trashed`);
      }
      return exists;
    } catch (error) {
      console.warn(`⚠️ [verifyFileExists] Error verifying file ${fileId}:`, error);
      // On error, assume file exists to avoid false positives
      return true;
    }
  }

  /**
   * Clean up orphaned entries from indexes (files that no longer exist in Google Drive)
   * This is the source of truth - if a file doesn't exist in Google Drive, remove it from all indexes
   */
  static async cleanupOrphanedIndexEntries(
    accessToken: string,
    pnIdentifier: string
  ): Promise<{ ownerIndexRemoved: number; publicIndexRemoved: number }> {
    try {
      let pnFolderId: string;
      let metadataFolderId: string;
      
      try {
        pnFolderId = await this.getOrCreatePNFolder(accessToken, pnIdentifier);
        metadataFolderId = await this.getOrCreateMetadataFolder(accessToken, pnFolderId);
      } catch (folderError: any) {
        // If token is expired, skip cleanup gracefully
        if (folderError?.message?.includes('Token expired') || folderError?.message?.includes('401') || folderError?.message?.includes('403')) {
          console.log('ℹ️ [cleanupOrphanedIndexEntries] Token expired - skipping cleanup (non-critical)');
          return { ownerIndexRemoved: 0, publicIndexRemoved: 0 };
        }
        throw folderError;
      }

      let ownerIndexRemoved = 0;
      let publicIndexRemoved = 0;

      // Clean up owner index
      try {
        const ownerIndex = await this.getOwnerFileIndex(accessToken, metadataFolderId, pnIdentifier);
        if (ownerIndex && ownerIndex.files) {
          const originalCount = ownerIndex.files.length;
          const verifiedFiles = [];

          // Verify each file exists in Google Drive
          console.log(`🔍 [cleanupOrphanedIndexEntries] Verifying ${ownerIndex.files.length} files in owner index...`);
          for (const fileEntry of ownerIndex.files) {
            const googleDriveFileId = fileEntry.googleDriveFileId;
            if (googleDriveFileId) {
              const exists = await this.verifyFileExists(accessToken, googleDriveFileId);
              if (exists) {
                verifiedFiles.push(fileEntry);
              } else {
                console.log(`🗑️ [cleanupOrphanedIndexEntries] Removing orphaned file from owner index: ${googleDriveFileId} (${(fileEntry as any).fileName || (fileEntry as any).originalName || 'unknown'})`);
                ownerIndexRemoved++;
              }
            } else {
              // Keep entries without googleDriveFileId (might be from other backends)
              verifiedFiles.push(fileEntry);
            }
          }

          if (verifiedFiles.length !== originalCount) {
            ownerIndex.files = verifiedFiles;
            ownerIndex.updatedAt = new Date().toISOString();
            await this.saveIndexFile(accessToken, metadataFolderId, this.OWNER_INDEX_FILE_NAME, ownerIndex);
            console.log(`✅ [cleanupOrphanedIndexEntries] Cleaned owner index: removed ${ownerIndexRemoved} orphaned file(s)`);
          }
        }
      } catch (ownerError) {
        console.warn('⚠️ [cleanupOrphanedIndexEntries] Failed to clean owner index:', ownerError);
      }

      // Clean up public index
      // Pass skipCleanup: true to avoid double cleanup (getPublicFileIndex no longer does cleanup, but keeping for safety)
      try {
        const publicIndex = await this.getPublicFileIndex(accessToken, metadataFolderId, pnIdentifier, true);
        if (publicIndex && publicIndex.files) {
          const originalCount = publicIndex.files.length;
          const verifiedFiles = [];

          // Verify each file exists in Google Drive
          console.log(`🔍 [cleanupOrphanedIndexEntries] Verifying ${publicIndex.files.length} files in public index...`);
          for (const fileEntry of publicIndex.files) {
            const googleDriveFileId = (fileEntry as any).googleDriveFileId;
            if (googleDriveFileId) {
              const exists = await this.verifyFileExists(accessToken, googleDriveFileId);
              if (exists) {
                verifiedFiles.push(fileEntry);
              } else {
                console.log(`🗑️ [cleanupOrphanedIndexEntries] Removing orphaned file from public index: ${googleDriveFileId} (${(fileEntry as any).fileName || (fileEntry as any).originalName || 'unknown'})`);
                publicIndexRemoved++;
              }
            } else {
              // Keep entries without googleDriveFileId
              verifiedFiles.push(fileEntry);
            }
          }

          if (verifiedFiles.length !== originalCount) {
            publicIndex.files = verifiedFiles;
            publicIndex.updatedAt = new Date().toISOString();
            await this.saveIndexFile(accessToken, metadataFolderId, this.PUBLIC_INDEX_FILE_NAME, publicIndex);
            console.log(`✅ [cleanupOrphanedIndexEntries] Cleaned public index: removed ${publicIndexRemoved} orphaned file(s)`);
          }
        }
      } catch (publicError) {
        console.warn('⚠️ [cleanupOrphanedIndexEntries] Failed to clean public index:', publicError);
      }

      return { ownerIndexRemoved, publicIndexRemoved };
    } catch (error) {
      console.error('❌ [cleanupOrphanedIndexEntries] Failed to cleanup indexes:', error);
      throw error;
    }
  }

  /**
   * Save index file to Google Drive (helper method)
   */
  private static async saveIndexFile(
    accessToken: string,
    metadataFolderId: string,
    fileName: string,
    index: any
  ): Promise<void> {
      const indexContent = JSON.stringify(index, null, 2);
      const indexBlob = new Blob([indexContent], { type: 'application/json' });

      // Check if index file exists
      const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${fileName}' and '${metadataFolderId}' in parents and trashed=false&fields=files(id)`,
        {
          headers: {
            'Authorization': `Bearer ${accessToken}`
          }
        }
      );

      if (!searchResponse.ok) {
        throw new Error('Failed to search for index file');
      }

      const searchData = await searchResponse.json();
      
      if (searchData.files && searchData.files.length > 0) {
        // Update existing index
        const fileId = searchData.files[0].id;

        const updateResponse = await fetch(
          `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`,
          {
            method: 'PATCH',
            headers: {
              'Authorization': `Bearer ${accessToken}`,
              'Content-Type': 'application/json; charset=UTF-8'
            },
            body: JSON.stringify(index)
          }
        );

        if (!updateResponse.ok) {
          const errorText = await updateResponse.text();
        console.error(`Failed to update ${fileName}:`, {
            status: updateResponse.status,
            statusText: updateResponse.statusText,
            errorText
          });
        throw new Error(`Failed to update ${fileName}`);
        }
      } else {
      // Create new index file
        const formData = new FormData();
        formData.append('metadata', new Blob([JSON.stringify({
        name: fileName,
          parents: [metadataFolderId]
        })], { type: 'application/json' }));
        formData.append('file', indexBlob);

        const createResponse = await fetch(
        `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart`,
          {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${accessToken}`
            },
            body: formData
          }
        );

        if (!createResponse.ok) {
        const errorText = await createResponse.text();
        console.error(`Failed to create ${fileName}:`, {
          status: createResponse.status,
          statusText: createResponse.statusText,
          errorText
        });
        throw new Error(`Failed to create ${fileName}`);
      }
    }
    
    // Make public index file publicly readable (only for public index)
    if (fileName === this.PUBLIC_INDEX_FILE_NAME) {
      try {
        const searchResponse = await fetch(
          `https://www.googleapis.com/drive/v3/files?q=name='${fileName}' and '${metadataFolderId}' in parents and trashed=false&fields=files(id)`,
          {
            headers: {
              'Authorization': `Bearer ${accessToken}`
            }
          }
        );
        
        if (searchResponse.ok) {
          const searchData = await searchResponse.json();
          if (searchData.files && searchData.files.length > 0) {
            const fileId = searchData.files[0].id;
          await fetch(
              `https://www.googleapis.com/drive/v3/files/${fileId}/permissions`,
            {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                role: 'reader',
                type: 'anyone'
              })
            }
          );
          }
        }
        } catch (permError) {
        // Permission might already exist, ignore
          console.warn('Failed to set public permissions:', permError);
        }
    }
  }
}
