name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build documentation
        run: |
          # Create docs directory for GitHub Pages
          mkdir -p docs-build
          cp -r docs/* docs-build/
          cp -r branding docs-build/
          cp -r tutorials docs-build/
          
      - name: Deploy to gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r docs-build/* .
          git add .
          git commit -m "Deploy documentation to GitHub Pages"
          git push origin gh-pages --force
